In [3]:
import pandas as pd

In [16]:
df_combined =  pd.read_csv("./data/combined_train_forecast.csv")

In [19]:
df_combined[df_combined["timeseries_id"] == '92715a77-8a65-0d88-5726-31836fb76dda'].tail(60)

,timeseries_id,date,city,shop,brand,container,sales,yhat,error,percentage_error
2249,92715a77-8a65-0d88-5726-31836fb76dda,2014-01-31,Thessaloniki,shop_4,orange-power,plastic,33976.80,NaN,NaN,NaN
2339,92715a77-8a65-0d88-5726-31836fb76dda,2014-02-28,Thessaloniki,shop_4,orange-power,plastic,34632.00,NaN,NaN,NaN
2429,92715a77-8a65-0d88-5726-31836fb76dda,2014-03-31,Thessaloniki,shop_4,orange-power,plastic,40111.74,NaN,NaN,NaN
2519,92715a77-8a65-0d88-5726-31836fb76dda,2014-04-30,Thessaloniki,shop_4,orange-power,plastic,48243.42,NaN,NaN,NaN
2609,92715a77-8a65-0d88-5726-31836fb76dda,2014-05-31,Thessaloniki,shop_4,orange-power,plastic,69006.37,NaN,NaN,NaN
2699,92715a77-8a65-0d88-5726-31836fb76dda,2014-06-30,Thessaloniki,shop_4,orange-power,plastic,67934.68,NaN,NaN,NaN
2789,92715a77-8a65-0d88-5726-31836fb76dda,2014-07-31,Thessaloniki,shop_4,orange-power,plastic,75778.45,NaN,NaN,NaN
2879,92715a77-8a65-0d88-5726-31836fb76dda,2014-08-31,Thessaloniki,shop_4,orange-power,plastic,66991.92,NaN,NaN,NaN
2969,92715a77-8a65-0d88-5726-31836fb76dda,2014-09-30,Thessaloniki,shop_4,orange-power,plastic,51198.29,NaN,NaN,NaN
3059,92715a77-8a65-0d88-5726-31836fb76dda,2014-10-31,Thessaloniki,shop_4,orange-power,plastic,46343.68,NaN,NaN,NaN
3149,92715a77-8a65-0d88-5726-31836fb76dda,2014-11-30,Thessaloniki,shop_4,orange-power,plastic,32806.20,NaN,NaN,NaN
3239,92715a77-8a65-0d88-5726-31836fb76dda,2014-12-31,Thessaloniki,shop_4,orange-power,plastic,42978.72,NaN,NaN,NaN
3329,92715a77-8a65-0d88-5726-31836fb76dda,2015-01-31,Thessaloniki,shop_4,orange-power,plastic,34276.06,NaN,NaN,NaN
3419,92715a77-8a65-0d88-5726-31836fb76dda,2015-02-28,Thessaloniki,shop_4,orange-power,plastic,35205.78,NaN,NaN,NaN
3509,92715a77-8a65-0d88-5726-31836fb76dda,2015-03-31,Thessaloniki,shop_4,orange-power,plastic,42185.88,NaN,NaN,NaN
3599,92715a77-8a65-0d88-5726-31836fb76dda,2015-04-30,Thessaloniki,shop_4,orange-power,plastic,52559.16,NaN,NaN,NaN
3689,92715a77-8a65-0d88-5726-31836fb76dda,2015-05-31,Thessaloniki,shop_4,orange-power,plastic,53225.76,NaN,NaN,NaN
3779,92715a77-8a65-0d88-5726-31836fb76dda,2015-06-30,Thessaloniki,shop_4,orange-power,plastic,74783.88,NaN,NaN,NaN
3869,92715a77-8a65-0d88-5726-31836fb76dda,2015-07-31,Thessaloniki,shop_4,orange-power,plastic,75762.26,NaN,NaN,NaN
3959,92715a77-8a65-0d88-5726-31836fb76dda,2015-08-31,Thessaloniki,shop_4,orange-power,plastic,65782.08,NaN,NaN,NaN
4049,92715a77-8a65-0d88-5726-31836fb76dda,2015-09-30,Thessaloniki,shop_4,orange-power,plastic,48763.50,NaN,NaN,NaN
4139,92715a77-8a65-0d88-5726-31836fb76dda,2015-10-31,Thessaloniki,shop_4,orange-power,plastic,47119.55,NaN,NaN,NaN
4229,92715a77-8a65-0d88-5726-31836fb76dda,2015-11-30,Thessaloniki,shop_4,orange-power,plastic,35624.11,NaN,NaN,NaN
4319,92715a77-8a65-0d88-5726-31836fb76dda,2015-12-31,Thessaloniki,shop_4,orange-power,plastic,46583.00,NaN,NaN,NaN
4409,92715a77-8a65-0d88-5726-31836fb76dda,2016-01-31,Thessaloniki,shop_4,orange-power,plastic,33778.01,NaN,NaN,NaN
4499,92715a77-8a65-0d88-5726-31836fb76dda,2016-02-29,Thessaloniki,shop_4,orange-power,plastic,32158.67,NaN,NaN,NaN
4589,92715a77-8a65-0d88-5726-31836fb76dda,2016-03-31,Thessaloniki,shop_4,orange-power,plastic,43974.56,NaN,NaN,NaN
4679,92715a77-8a65-0d88-5726-31836fb76dda,2016-04-30,Thessaloniki,shop_4,orange-power,plastic,52967.60,NaN,NaN,NaN
4769,92715a77-8a65-0d88-5726-31836fb76dda,2016-05-31,Thessaloniki,shop_4,orange-power,plastic,72263.91,NaN,NaN,NaN
4859,92715a77-8a65-0d88-5726-31836fb76dda,2016-06-30,Thessaloniki,shop_4,orange-power,plastic,34656.16,NaN,NaN,NaN
4949,92715a77-8a65-0d88-5726-31836fb76dda,2016-07-31,Thessaloniki,shop_4,orange-power,plastic,80036.00,NaN,NaN,NaN
5039,92715a77-8a65-0d88-5726-31836fb76dda,2016-08-31,Thessaloniki,shop_4,orange-power,plastic,67445.70,NaN,NaN,NaN
5129,92715a77-8a65-0d88-5726-31836fb76dda,2016-09-30,Thessaloniki,shop_4,orange-power,plastic,53292.82,NaN,NaN,NaN
5219,92715a77-8a65-0d88-5726-31836fb76dda,2016-10-31,Thessaloniki,shop_4,orange-power,plastic,47035.64,NaN,NaN,NaN
5309,92715a77-8a65-0d88-5726-31836fb76dda,2016-11-30,Thessaloniki,shop_4,orange-power,plastic,33523.84,NaN,NaN,NaN
5399,92715a77-8a65-0d88-5726-31836fb76dda,2016-12-31,Thessaloniki,shop_4,orange-power,plastic,42774.75,NaN,NaN,NaN
5489,92715a77-8a65-0d88-5726-31836fb76dda,2017-01-31,Thessaloniki,shop_4,orange-power,plastic,34484.32,NaN,NaN,NaN
5579,92715a77-8a65-0d88-5726-31836fb76dda,2017-02-28,Thessaloniki,shop_4,orange-power,plastic,35389.12,NaN,NaN,NaN
5669,92715a77-8a65-0d88-5726-31836fb76dda,2017-03-31,Thessaloniki,shop_4,orange-power,plastic,45780.80,NaN,NaN,NaN
5759,92715a77-8a65-0d88-5726-31836fb76dda,2017-04-30,Thessaloniki,shop_4,orange-power,plastic,55726.38,NaN,NaN,NaN
5849,92715a77-8a65-0d88-5726-31836fb76dda,2017-05-31,Thessaloniki,shop_4,orange-power,plastic,73643.58,NaN,NaN,NaN
5939,92715a77-8a65-0d88-5726-31836fb76dda,2017-06-30,Thessaloniki,shop_4,orange-power,plastic,75878.00,NaN,NaN,NaN
6029,92715a77-8a65-0d88-5726-31836fb76dda,2017-07-31,Thessaloniki,shop_4,orange-power,plastic,67480.64,NaN,NaN,NaN
6119,92715a77-8a65-0d88-5726-31836fb76dda,2017-08-31,Thessaloniki,shop_4,orange-power,plastic,72702.24,NaN,NaN,NaN
6209,92715a77-8a65-0d88-5726-31836fb76dda,2017-09-30,Thessaloniki,shop_4,orange-power,plastic,54401.10,NaN,NaN,NaN
6299,92715a77-8a65-0d88-5726-31836fb76dda,2017-10-31,Thessaloniki,shop_4,orange-power,plastic,49702.90,NaN,NaN,NaN
6389,92715a77-8a65-0d88-5726-31836fb76dda,2017-11-30,Thessaloniki,shop_4,orange-power,plastic,30010.68,NaN,NaN,NaN
6479,92715a77-8a65-0d88-5726-31836fb76dda,2017-12-31,Thessaloniki,shop_4,orange-power,plastic,49048.40,NaN,NaN,NaN
6569,92715a77-8a65-0d88-5726-31836fb76dda,2018-01-31,Thessaloniki,shop_4,orange-power,plastic,36771.24,35485.821402,1285.418598,3.495717
6659,92715a77-8a65-0d88-5726-31836fb76dda,2018-02-28,Thessaloniki,shop_4,orange-power,plastic,37593.60,37009.419845,584.180155,1.553935
6749,92715a77-8a65-0d88-5726-31836fb76dda,2018-03-31,Thessaloniki,shop_4,orange-power,plastic,45288.21,44347.969789,940.240211,2.076126
6839,92715a77-8a65-0d88-5726-31836fb76dda,2018-04-30,Thessaloniki,shop_4,orange-power,plastic,55880.01,53914.399801,1965.610199,3.517555
6928,92715a77-8a65-0d88-5726-31836fb76dda,2018-05-31,Thessaloniki,shop_4,orange-power,plastic,75429.00,65588.775054,9840.224946,13.045679
7018,92715a77-8a65-0d88-5726-31836fb76dda,2018-06-30,Thessaloniki,shop_4,orange-power,plastic,78063.66,72073.151914,5990.508086,7.673876
7108,92715a77-8a65-0d88-5726-31836fb76dda,2018-07-31,Thessaloniki,shop_4,orange-power,plastic,71258.75,76679.426962,-5420.676962,-7.607033
7198,92715a77-8a65-0d88-5726-31836fb76dda,2018-08-31,Thessaloniki,shop_4,orange-power,plastic,73584.70,69478.876873,4105.823127,5.579724
7288,92715a77-8a65-0d88-5726-31836fb76dda,2018-09-30,Thessaloniki,shop_4,orange-power,plastic,54264.76,52787.553211,1477.206789,2.722221
7377,92715a77-8a65-0d88-5726-31836fb76dda,2018-10-31,Thessaloniki,shop_4,orange-power,plastic,50398.74,48566.763368,1831.976632,3.634965
7467,92715a77-8a65-0d88-5726-31836fb76dda,2018-11-30,Thessaloniki,shop_4,orange-power,plastic,35086.80,36075.221843,-988.421843,-2.817076
7556,92715a77-8a65-0d88-5726-31836fb76dda,2018-12-31,Thessaloniki,shop_4,orange-power,plastic,50097.30,47789.992184,2307.307816,4.605653

In [10]:
df_train = df_train[df_train["date"].notna()]

In [11]:
df_train["date"].max()

'31/12/17'

In [13]:
df_train.columns

Index(['id', 'date', 'city', 'lat', 'long', 'pop', 'shop', 'brand',
       'container', 'capacity', 'price', 'quantity'],
      dtype='object')

In [12]:
df_forecasts.columns

Index(['date', 'city', 'shop', 'brand', 'container', 'sales', 'yhat', 'error',
       'percentage_error'],
      dtype='object')

In [ ]:
from dotenv import load_dotenv

sys_prompt = """You are a helpful assistant, 
            which will help the user to get information about the sales 
            and sales forecasts of the company. 
            You have access to sales data and sales forecasts data.
            the tools you have access to are:

            1. get_sales_data: This tool will help you to get the sales data for a given timeseries_id and date range.
            2. get_sales_forecast: This tool will help you to get the sales forecast data for a given timeseries_id and date range.
            3. calculate sales_growth: This tool will help you to calculate the sales growth for a given timeseries_id and date range.
            4. calculate forecast_accuracy: This tool will help you to calculate the forecast accuracy for a given timeseries_id and date range.
            5. filter_the_data : this will help you to filter the data based on the given criteria. (READ the criteria from the user input and apply the filter on the data)
            6. plot_the_data : this will help you to plot the data based on the given criteria. (READ the criteria from the user input and apply the filter on the data)
            7. create_report : this will help you to create a report based on the given criteria. (READ the criteria from the user input and apply the filter on the data)


            the data you have acess to is in the form of a pandas dataframe.
            NOTE -> the data you have access to is a monthly data and have yhat = None value for the historical data and yhat = forecasted value for the future data.
            

            """
load_dotenv() # Load environment variables from a .env file

# pip install -qU langchain langchain-openrouter
from langchain.agents import create_agent
from sales_agent_tools import get_sales_data, get_sales_forecast, calculate_sales_growth, calculate_forecast_accuracy, filter_the_data, plot_the_data, create_report

def get_weather(city: str) -> str:
    """Get weather for a given city."""
    return f"It's always sunny in {city}!"

agent = create_agent(
    model="openrouter:anthropic/claude-sonnet-4-6",
    tools=[get_sales_data, get_sales_forecast, calculate_sales_growth, calculate_forecast_accuracy, filter_the_data, plot_the_data, create_report],
    system_prompt=sys_prompt,
)

result = agent.invoke(
    {"messages": [{"role": "user", "content": "What are the sales figures for Q1 2023?"}]}
)
print(result["messages"][-1].content_blocks)

[{'type': 'text', 'text': "It looks like it's **sunny** in San Francisco right now! 🌞 It's a great day to get outside and enjoy the city. Is there anything else you'd like to know?"}]

In [20]:
df_combined

,timeseries_id,date,city,shop,brand,container,sales,yhat,error,percentage_error
0,158b8554-6512-94d3-5e95-932ae4475db8,2012-01-31,Athens,shop_1,adult-cola,can,10021.44,NaN,NaN,NaN
1,be6dccfb-4216-89bc-8daf-40bcd1e51a41,2012-01-31,Athens,shop_1,adult-cola,glass,20050.00,NaN,NaN,NaN
2,e51da593-1565-a1a0-18de-ae185db60c7c,2012-01-31,Athens,shop_1,adult-cola,plastic,31183.95,NaN,NaN,NaN
3,63e620e9-7242-9e19-a8ea-5131c994a9c9,2012-01-31,Athens,shop_1,gazoza,can,6546.80,NaN,NaN,NaN
4,0c1280bd-7701-c00f-e278-ea11f9c6d59d,2012-01-31,Athens,shop_1,gazoza,glass,21919.66,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7552,3891a69f-1224-7821-cde5-66154f21ce97,2018-12-31,Thessaloniki,shop_4,lemon-boost,glass,26161.86,27578.541092,-1416.681092,-5.415063
7553,378a589b-cd2a-c64d-f621-cee562add21d,2018-12-31,Thessaloniki,shop_4,lemon-boost,plastic,46912.32,49431.287175,-2518.967175,-5.369522
7554,29189770-aefc-66e4-ab57-1ded9f64d82c,2018-12-31,Thessaloniki,shop_4,orange-power,can,23475.85,27316.669759,-3840.819759,-16.360727
7555,4827160d-03d6-a566-722d-a698c0549595,2018-12-31,Thessaloniki,shop_4,orange-power,glass,27665.00,33524.910647,-5859.910647,-21.181676
7556,92715a77-8a65-0d88-5726-31836fb76dda,2018-12-31,Thessaloniki,shop_4,orange-power,plastic,50097.30,47789.992184,2307.307816,4.605653